### ISSUE TITLE
Latest binary (Feb 2014) crashes on 10.10

### ISSUE THREAD

**Issue by p2** [Barbatos/UrTUpdater#1]
Since the Updater from the official website always fails for me I tried the binary on here. Crashes while the "Updating..." spinning animation is showing. Crash log here: https://gist.github.com/p2/69cab5e81c245944a2ab

**Comment by Barbatos** [comment]
This should be fixed in the latest binary (Jan 2016). Please do not hesitate to reopen the issue if you encounter another crash.

**Comment by p2** [comment]
Great, works fine, thanks!
